Restrucured how $extra var is set for pipx

diff --git a/.chezmoiscripts/run_onchange-darwin-install-packages.sh.tmpl b/.chezmoiscripts/run_onchange-darwin-install-packages.sh.tmpl
--- a/.chezmoiscripts/run_onchange-darwin-install-packages.sh.tmpl
+++ b/.chezmoiscripts/run_onchange-darwin-install-packages.sh.tmpl
@@ -44,14 +44,12 @@ fi
 # Install Python packages
 {{- range $pkg := .python_packages }}
 if command -v pipx &> /dev/null; then
+  {{ $extra := "" }}
   {{- if hasKey $pkg "extra" }}
   {{- $extra := $pkg.extra | join "," -}}
-  echo "Installing Python package with extras: {{ $pkg.name }}[{{ $extra }}]"
-  pipx install --system-site-packages "{{ $pkg.name }}[{{ $extra }}]" || echo "Failed to install Python package: {{ $pkg }}"
-  {{- else }}
-  echo "Installing Python package: {{ $pkg.name }}"
-  pipx install --system-site-packages {{ $pkg.name }} || echo "Failed to install Python package: {{ $pkg }}"
   {{- end }}
+  echo "Installing Python package with extras: {{ $pkg.name }}{{ $extra }}"
+  pipx install --system-site-packages "{{ $pkg.name }}[{{ $extra }}]" || echo "Failed to install Python package: {{ $pkg }}"
 fi
 {{- end }}
 {{- end }}
