Added ansible, reverted alloy brew back

diff --git a/.chezmoiscripts/run_onchange-darwin-install-packages.sh.tmpl b/.chezmoiscripts/run_onchange-darwin-install-packages.sh.tmpl
--- a/.chezmoiscripts/run_onchange-darwin-install-packages.sh.tmpl
+++ b/.chezmoiscripts/run_onchange-darwin-install-packages.sh.tmpl
@@ -49,7 +49,7 @@ if command -v pipx &> /dev/null; then
   {{- $extras := $pkg.extras | join "," -}}
   {{- end }}
   echo "Installing Python package with extras: {{ $pkg.name }}{{ $extras }}"
-  pipx install --system-site-packages "{{ $pkg.name }}{{ $extras }}=={{ $pkg.version }}" || echo "Failed to install Python package: {{ $pkg }}"
+  pipx install --include-deps --system-site-packages "{{ $pkg.name }}{{ $extras }}=={{ $pkg.version }}" || echo "Failed to install Python package: {{ $pkg }}"
 fi
 {{- end }}
 {{- end }}
