Install node packages

diff --git a/.chezmoiscripts/run_onchange-darwin-install-packages.sh.tmpl b/.chezmoiscripts/run_onchange-darwin-install-packages.sh.tmpl
--- a/.chezmoiscripts/run_onchange-darwin-install-packages.sh.tmpl
+++ b/.chezmoiscripts/run_onchange-darwin-install-packages.sh.tmpl
@@ -69,4 +69,18 @@ fi
 {{ end -}}
 {{ end -}}
 
+# install npm packages
+{{ if .npm_packages -}}
+echo "Installing npm packages"
+
+{{ range $pkg := .npm_packages -}}
+if ! npm list -g --depth=0 | grep -q {{ $pkg.name }}; then
+  echo "Installing npm package: {{ $pkg.name }}"
+  npm install -g {{ $pkg.name }}@{{ $pkg.version }} || echo "Failed to install npm package: {{ $pkg.name }}"
+else
+  echo "NPM package {{ $pkg.name }} is already installed."
+fi
+{{ end -}}
+{{ end -}}
+
 {{- end -}}
