Added --system flag to uv pip install

diff --git a/.chezmoiscripts/run_onchange_darwin-install-packages.sh.tmpl b/.chezmoiscripts/run_onchange_darwin-install-packages.sh.tmpl
--- a/.chezmoiscripts/run_onchange_darwin-install-packages.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_darwin-install-packages.sh.tmpl
@@ -40,15 +40,15 @@ fi
   {{- end }}
 {{- end }}
 
-{{- if .python_packages -}}
+{{- if .python_packages }}
 # Install Python packages
-{{- range $pkg := .python_packages -}}
+{{- range $pkg := .python_packages }}
 # check if uv is installed
 if command -v uv &> /dev/null; then
   echo "Installing Python package: {{ $pkg }} using uv"
-  uv pip install {{ $pkg }} || echo "Failed to install Python package: {{ $pkg }}"
+  uv pip install --system {{ $pkg }} || echo "Failed to install Python package: {{ $pkg }}"
 fi
-{{- end -}}
-{{- end -}}
+{{- end }}
+{{- end }}
 
 {{- end -}}
