Updated run_onchange script and brews.yaml

diff --git a/run_onchange_darwin-install-packages.sh.tmpl b/run_onchange_darwin-install-packages.sh.tmpl
--- a/run_onchange_darwin-install-packages.sh.tmpl
+++ b/run_onchange_darwin-install-packages.sh.tmpl
@@ -23,6 +23,20 @@ EOF
 
 # install krew plugins
 if [ -f $HOME/.krew.txt ]; then
-  kubectl krew install < $HOME/.krew.txt
+  #kubectl krew install < $HOME/.krew.txt
+  echo "Reconciling krew plugins"
+  while read -r plugin; do
+    if ! kubectl krew list | grep -q "$plugin"; then
+      echo "Installing krew plugin: $plugin"
+      kubectl krew install "$plugin" 1>&2>/dev/null
+      if [ $? -ne 0 ]; then
+        echo "Failed to install krew plugin: $plugin"
+      else
+        echo "Successfully installed krew plugin: $plugin"
+      fi
+    else
+      echo "Krew plugin $plugin is already installed."
+    fi
+  done < $HOME/.krew.txt
 fi
 {{- end -}}
